import path from "node:path";
import type {
  Attributes,
  BlockNode,
  CitationNode,
  DocumentNode,
  FencedDivNode,
  FigureNode,
  HeadingNode,
  InlineNode,
  ListNode,
  MathBlockNode,
  ParagraphNode,
  TableNode
} from "../core/ast.js";
import type { Diagnostic } from "../core/diagnostics.js";
import type { BuildArtifact, CompileOptions } from "../core/project.js";
import { resolveTemplate, type TemplateManifest } from "../templates/registry.js";
import { escapeLatex, latexColor } from "./escape.js";

export interface LatexOutput {
  tex: string;
  requiredPackages: string[];
  buildSteps: string[];
  artifacts: BuildArtifact;
  diagnostics: Diagnostic[];
}

interface LatexContext {
  template: TemplateManifest;
  packages: Set<string>;
  theoremNames: Set<string>;
  hasIndex: boolean;
  hasGlossary: boolean;
  hasBibliography: boolean;
  options: CompileOptions;
}

export function emitLatex(document: DocumentNode, options: CompileOptions): LatexOutput {
  const template = resolveTemplate(document.frontmatter?.data.template);
  const ctx: LatexContext = {
    template,
    packages: new Set(["inputenc", "fontenc", "babel", "hyperref"]),
    theoremNames: new Set(),
    hasIndex: false,
    hasGlossary: false,
    hasBibliography: false,
    options
  };
  scanFeatures(document.children, ctx);
  const preamble = emitPreamble(document, ctx);
  const body = document.children.map((node) => emitBlock(node, ctx)).filter(Boolean).join("\n\n");
  const tex = `${preamble}\n\\begin{document}\n\n${emitTitle(document, template)}${body}\n\n\\end{document}\n`;
  const mainName = document.sourceFiles[0] ? path.basename(document.sourceFiles[0], path.extname(document.sourceFiles[0])) : "main";
  const texPath = path.join(options.outputDir, `${mainName}.tex`);
  const pdfPath = path.join(options.outputDir, `${mainName}.pdf`);

  return {
    tex,
    requiredPackages: [...ctx.packages],
    buildSteps: buildSteps(ctx, texPath),
    artifacts: { texPath, pdfPath, auxFiles: auxFiles(options.outputDir, mainName) },
    diagnostics: document.diagnostics
  };
}

function emitPreamble(document: DocumentNode, ctx: LatexContext): string {
  const data = document.frontmatter?.data ?? {};
  const language = String(data.language ?? ctx.template.defaultStyle.language);
  const babelLanguage = language.startsWith("es") ? "spanish" : "english";
  const classOptions = [ctx.template.defaultStyle.fontSize, ...ctx.template.classOptions]
    .filter(Boolean)
    .filter((value, index, values) => values.indexOf(value) === index)
    .join(",");
  const lines = [
    `% Generated by KUI v0.x LaTeX bridge`,
    `\\documentclass[${classOptions}]{${ctx.template.documentClass}}`,
    `\\usepackage[utf8]{inputenc}`,
    `\\usepackage[T1]{fontenc}`,
    `\\usepackage[${babelLanguage}]{babel}`,
    `\\usepackage{csquotes}`
  ];

  if (ctx.packages.has("amsmath")) lines.push(`\\usepackage{amsmath,amssymb,amsthm}`);
  if (ctx.packages.has("graphicx")) lines.push(`\\usepackage{graphicx}`, `\\usepackage{caption}`, `\\usepackage{subcaption}`);
  if (ctx.packages.has("booktabs")) lines.push(`\\usepackage{booktabs}`, `\\usepackage{longtable}`);
  if (ctx.packages.has("xcolor")) lines.push(`\\usepackage[dvipsnames,svgnames]{xcolor}`);
  if (ctx.packages.has("listings")) lines.push(`\\usepackage{listings}`);
  if (ctx.packages.has("tcolorbox")) lines.push(`\\usepackage[most]{tcolorbox}`);
  if (ctx.packages.has("tikz")) lines.push(`\\usepackage{tikz}`, `\\usetikzlibrary{shapes,arrows,positioning,shadows}`);
  if (ctx.packages.has("ulem")) lines.push(`\\usepackage[normalem]{ulem}`);
  if (ctx.packages.has("geometry")) lines.push(`\\usepackage[a4paper,margin=2.5cm]{geometry}`);
  if (ctx.packages.has("fancyhdr")) lines.push(`\\usepackage{fancyhdr}`);
  if (ctx.hasIndex) lines.push(`\\usepackage{imakeidx}`, `\\makeindex`);
  if (ctx.hasGlossary) lines.push(`\\usepackage[acronym]{glossaries}`, `\\makeglossaries`);
  if (ctx.hasBibliography) {
    const style = biblatexStyle(String(data.csl ?? data.bibStyle ?? "apa"));
    lines.push(`\\usepackage[backend=biber,style=${style}]{biblatex}`);
    for (const bib of normalizeBibFiles(data.bib)) {
      lines.push(`\\addbibresource{${escapeLatex(resolveSourceRelativePath(bib, document, ctx))}}`);
    }
  }

  for (const [name, color] of Object.entries(ctx.template.defaultStyle.colors)) {
    if (/^#[0-9a-f]{6}$/i.test(color)) {
      lines.push(`\\definecolor{${name}}{HTML}{${color.slice(1).toUpperCase()}}`);
    }
  }

  emitTheorems(ctx, lines);
  lines.push(`\\usepackage{hyperref}`);
  return lines.join("\n");
}

function emitTitle(document: DocumentNode, template: TemplateManifest): string {
  const data = document.frontmatter?.data ?? {};
  const title = escapeLatex(String(data.title ?? "Untitled KUI Document"));
  const author = Array.isArray(data.author)
    ? data.author.map((item) => typeof item === "string" ? item : (item as Record<string, unknown>).name).join(", ")
    : String(data.author ?? "");
  const date = escapeLatex(String(data.date ?? "\\today"));
  const titleBlock = [`\\title{${title}}`, `\\author{${escapeLatex(author)}}`, `\\date{${date}}`, `\\maketitle`, ""];
  if (template.id === "tesis-unsaac") {
    const asesor = data.asesor ? `\\noindent\\textbf{Asesor:} ${escapeLatex(String(data.asesor))}\\\\\n` : "";
    const institucion = data.institucion ? `\\noindent\\textbf{Institución:} ${escapeLatex(String(data.institucion))}\\\\\n` : "";
    return `${titleBlock.join("\n")}${institucion}${asesor}\\newpage\n\n`;
  }
  return `${titleBlock.join("\n")}\n`;
}

function emitBlock(node: BlockNode, ctx: LatexContext): string {
  switch (node.kind) {
    case "Heading":
      return emitHeading(node);
    case "Paragraph":
      return emitParagraph(node, ctx);
    case "List":
      return emitList(node, ctx);
    case "Blockquote":
      return `\\begin{quote}\n${node.children.map((child) => emitBlock(child, ctx)).join("\n\n")}\n\\end{quote}`;
    case "Callout":
      return emitCallout(node.calloutType, node.children.map((child) => emitBlock(child, ctx)).join("\n\n"));
    case "CodeBlock":
      if (node.language === "tikz") return `\\begin{tikzpicture}\n${node.content}\n\\end{tikzpicture}`;
      return `\\begin{lstlisting}[language=${node.language ?? ""}]\n${node.content}\n\\end{lstlisting}`;
    case "MathBlock":
      return emitMathBlock(node);
    case "Figure":
      return emitFigure(node, ctx);
    case "Table":
      return emitTable(node, ctx);
    case "FencedDiv":
      return emitFencedDiv(node, ctx);
    case "Directive":
      return emitDirective(node.name, node.args);
    case "FootnoteDef":
      return "";
    case "HorizontalRule":
      return `\\rule{\\linewidth}{0.4pt}`;
  }
}

function emitHeading(node: HeadingNode): string {
  const title = emitInline(node.title);
  const label = node.attrs?.id ? `\n\\label{${escapeLatex(node.attrs.id)}}` : "";
  if (node.attrs?.classes.includes("part")) return `\\part{${title}}${label}`;
  if (node.attrs?.classes.includes("chapter")) return `\\chapter{${title}}${label}`;
  if (node.attrs?.classes.includes("appendix")) return `\\appendix\n\\chapter{${title}}${label}`;
  const commands = ["section", "subsection", "subsubsection", "paragraph", "subparagraph", "subparagraph"];
  return `\\${commands[node.level - 1]}{${title}}${label}`;
}

function emitParagraph(node: ParagraphNode, _ctx: LatexContext): string {
  return emitStyledInline(node.children, node.attrs);
}

function emitList(node: ListNode, ctx: LatexContext): string {
  const env = node.ordered ? "enumerate" : "itemize";
  const items = node.items.map((item) => {
    const marker = node.task ? `[${item.checked ? "$\\boxtimes$" : "$\\square$"}]` : "";
    return `  \\item${marker} ${emitInline(item.children)}`;
  }).join("\n");
  return `\\begin{${env}}\n${items}\n\\end{${env}}`;
}

function emitMathBlock(node: MathBlockNode): string {
  const label = node.attrs?.id ? `\\label{${escapeLatex(node.attrs.id)}}\n` : "";
  const env = node.attrs?.id ? "equation" : "equation*";
  return `\\begin{${env}}\n${label}${node.content}\n\\end{${env}}`;
}

function emitFigure(node: FigureNode, _ctx: LatexContext): string {
  const width = node.attrs?.normalized.width ?? "0.8\\linewidth";
  const normalizedWidth = width.endsWith("%") ? `${Number.parseFloat(width) / 100}\\linewidth` : width;
  const label = node.attrs?.id ? `\n  \\label{${escapeLatex(node.attrs.id)}}` : "";
  const imagePath = resolveNodeRelativePath(node.path, node, _ctx);
  return [
    `\\begin{figure}[h]`,
    `  \\centering`,
    `  \\includegraphics[width=${normalizedWidth}]{${escapeLatex(imagePath)}}`,
    `  \\caption{${emitInline(node.caption)}}${label}`,
    `\\end{figure}`
  ].join("\n");
}

function emitTable(node: TableNode, _ctx: LatexContext): string {
  const columns = node.headers.map(() => "l").join("") || "l";
  const header = node.headers.map(emitInline).join(" & ");
  const rows = node.rows.map((row) => `${row.map(emitInline).join(" & ")} \\\\`).join("\n");
  const caption = node.caption ? `  \\caption{${emitInline(node.caption)}}\n` : "";
  const label = node.attrs?.id ? `  \\label{${escapeLatex(node.attrs.id)}}\n` : "";
  return [
    `\\begin{table}[h]`,
    `  \\centering`,
    caption.trimEnd(),
    label.trimEnd(),
    `  \\begin{tabular}{${columns}}`,
    `    \\toprule`,
    `    ${header} \\\\`,
    `    \\midrule`,
    rows.split("\n").map((row) => `    ${row}`).join("\n"),
    `    \\bottomrule`,
    `  \\end{tabular}`,
    `\\end{table}`
  ].filter(Boolean).join("\n");
}

function emitFencedDiv(node: FencedDivNode, ctx: LatexContext): string {
  const body = node.children.map((child) => emitBlock(child, ctx)).join("\n\n");
  const name = node.canonicalName ?? node.name;
  const label = node.attrs?.id ? `\\label{${escapeLatex(node.attrs.id)}}\n` : "";
  if (["abstract", "theorem", "definition", "proof", "lemma", "corollary"].includes(name)) {
    const env = name === "abstract" ? "abstract" : name;
    return `\\begin{${env}}\n${label}${body}\n\\end{${env}}`;
  }
  if (name === "center") return `\\begin{center}\n${body}\n\\end{center}`;
  if (name === "box") return `\\begin{tcolorbox}[title=${escapeLatex(node.attrs?.normalized.title ?? "")}]\n${body}\n\\end{tcolorbox}`;
  if (name === "shape") return emitShape(node, body);
  if (name === "note") return emitCallout("NOTE", body);
  if (name === "warning") return emitCallout("WARNING", body);
  if (name === "todo") return emitCallout("TODO", body);
  return body;
}

function emitShape(node: FencedDivNode, body: string): string {
  const type = node.attrs?.normalized.type ?? "rectangle";
  const tikzShape = type === "square" ? "rectangle" : type;
  const color = node.attrs?.normalized.color ?? "black";
  const fill = node.attrs?.normalized.fill ?? "white";
  return `\\begin{tikzpicture}\n\\node[${tikzShape}, draw=${color}, fill=${fill}, align=center, minimum size=2cm] {${body.replace(/\n+/g, " ")}};\n\\end{tikzpicture}`;
}

function emitCallout(type: string, body: string): string {
  const title = type === "WARNING" ? "Atención" : type === "TODO" ? "Pendiente" : "Nota";
  const color = type === "WARNING" ? "yellow" : type === "TODO" ? "orange" : "blue";
  return `\\begin{tcolorbox}[colback=${color}!5,colframe=${color}!60!black,title=${title}]\n${body}\n\\end{tcolorbox}`;
}

function emitDirective(name: string, args: string): string {
  switch (name) {
    case "toc":
      return "\\tableofcontents";
    case "lof":
      return "\\listoffigures";
    case "lot":
      return "\\listoftables";
    case "index":
      return "\\printindex";
    case "glossary":
      return "\\printglossary";
    case "bibliography":
      return "\\printbibliography";
    case "appendix":
      return "\\appendix";
    case "newpage":
      return "\\newpage";
    case "clearpage":
      return "\\clearpage";
    case "include":
      return `% include resolved before parsing: ${escapeLatex(args)}`;
    case "vspace":
      return `\\vspace{${escapeLatex(args)}}`;
    default:
      return `% unknown directive`;
  }
}

function emitInline(nodes: InlineNode[]): string {
  return nodes.map((node) => {
    switch (node.kind) {
      case "Text":
        return escapeLatex(node.value);
      case "Bold":
        return `\\textbf{${emitInline(node.children)}}`;
      case "Italic":
        return `\\emph{${emitInline(node.children)}}`;
      case "InlineCode":
        return `\\texttt{${escapeLatex(node.value)}}`;
      case "Link":
        return `\\href{${escapeLatex(node.url)}}{${emitInline(node.children)}}`;
      case "ImageInline":
        return `\\includegraphics{${escapeLatex(node.url)}}`;
      case "Span":
        return emitStyledInline(node.children, node.attrs);
      case "MathInline":
        return `$${node.content}$`;
      case "Citation":
        return emitCitation(node);
      case "CrossRef":
        return node.refType === "eq" ? `\\eqref{${escapeLatex(node.id)}}` : `\\ref{${escapeLatex(node.id)}}`;
      case "FootnoteRef":
        return `\\footnote{${escapeLatex(node.id)}}`;
    }
  }).join("");
}

function emitStyledInline(children: InlineNode[], attrs?: Attributes): string {
  let value = emitInline(children);
  if (!attrs) return value;
  const normalized = attrs.normalized;
  if (attrs.classes.includes("smallcaps") || normalized.style === "smallcaps") value = `\\textsc{${value}}`;
  if (attrs.classes.includes("underline")) value = `\\uline{${value}}`;
  if (normalized.weight === "bold") value = `\\textbf{${value}}`;
  if (normalized.style === "italic") value = `\\emph{${value}}`;
  if (normalized.color) value = `\\textcolor${latexColor(normalized.color)}{${value}}`;
  if (normalized.bg) value = `\\colorbox{${escapeLatex(normalized.bg)}}{${value}}`;
  return value;
}

function emitCitation(node: CitationNode): string {
  const keys = node.items.map((item) => item.key).join(",");
  const locator = node.items.length === 1 && node.items[0].locator ? `[${escapeLatex(node.items[0].locator)}]` : "";
  return node.citationStyle === "intext" ? `\\textcite${locator}{${keys}}` : `\\autocite${locator}{${keys}}`;
}

function scanFeatures(blocks: BlockNode[], ctx: LatexContext): void {
  const scanInline = (nodes: InlineNode[]): void => {
    for (const node of nodes) {
      if (node.kind === "MathInline") ctx.packages.add("amsmath");
      if (node.kind === "Citation") ctx.hasBibliography = true;
      if (node.kind === "CrossRef" || node.kind === "Link") ctx.packages.add("hyperref");
      if (node.kind === "Span") {
        if (node.attrs?.normalized.color || node.attrs?.normalized.bg) ctx.packages.add("xcolor");
        if (node.attrs?.classes.includes("underline")) ctx.packages.add("ulem");
        scanInline(node.children);
      }
      if ("children" in node && Array.isArray(node.children)) scanInline(node.children as InlineNode[]);
    }
  };
  for (const block of blocks) {
    if (block.kind === "CodeBlock") ctx.packages.add(block.language === "tikz" ? "tikz" : "listings");
    if (block.kind === "MathBlock") ctx.packages.add("amsmath");
    if (block.kind === "Figure") ctx.packages.add("graphicx");
    if (block.kind === "Table") ctx.packages.add("booktabs");
    if (block.kind === "Callout") ctx.packages.add("tcolorbox");
    if (block.kind === "FencedDiv") {
      if (["theorem", "definition", "proof", "lemma", "corollary"].includes(block.canonicalName ?? block.name)) {
        ctx.packages.add("amsmath");
        ctx.theoremNames.add(block.canonicalName ?? block.name);
      }
      if (["box", "note", "warning", "todo"].includes(block.canonicalName ?? block.name)) ctx.packages.add("tcolorbox");
      if ((block.canonicalName ?? block.name) === "shape") ctx.packages.add("tikz");
      scanFeatures(block.children, ctx);
    }
    if (block.kind === "Directive") {
      if (block.name === "bibliography") ctx.hasBibliography = true;
      if (block.name === "index") ctx.hasIndex = true;
      if (block.name === "glossary") ctx.hasGlossary = true;
    }
    if (block.kind === "Heading") scanInline(block.title);
    if (block.kind === "Paragraph" || block.kind === "FootnoteDef") scanInline(block.children);
    if (block.kind === "Figure") scanInline(block.caption);
    if (block.kind === "Table") {
      block.headers.flat().forEach((node) => scanInline([node]));
      block.rows.flat(2).forEach((node) => scanInline([node]));
      if (block.caption) scanInline(block.caption);
    }
    if (block.kind === "List") block.items.forEach((item) => scanInline(item.children));
    if (block.kind === "Blockquote" || block.kind === "Callout") scanFeatures(block.children, ctx);
  }
}

function emitTheorems(ctx: LatexContext, lines: string[]): void {
  const mapping: Record<string, string> = {
    theorem: "Teorema",
    definition: "Definición",
    lemma: "Lema",
    corollary: "Corolario"
  };
  for (const name of ctx.theoremNames) {
    if (name === "proof" || name === "abstract") continue;
    lines.push(`\\newtheorem{${name}}{${mapping[name] ?? name}}[section]`);
  }
}

function buildSteps(ctx: LatexContext, texPath: string): string[] {
  const engine = ctx.options.pdfEngine ?? ctx.template.pdfEngine;
  const base = path.basename(texPath, ".tex");
  const dir = path.dirname(texPath);
  const steps = [`${engine} -interaction=nonstopmode -output-directory ${dir} ${texPath}`];
  if (ctx.hasBibliography) steps.push(`biber ${path.join(dir, base)}`);
  if (ctx.hasIndex) steps.push(`makeindex ${path.join(dir, `${base}.idx`)}`);
  if (ctx.hasGlossary) steps.push(`makeglossaries ${path.join(dir, base)}`);
  steps.push(`${engine} -interaction=nonstopmode -output-directory ${dir} ${texPath}`);
  steps.push(`${engine} -interaction=nonstopmode -output-directory ${dir} ${texPath}`);
  return steps;
}

function auxFiles(outputDir: string, base: string): string[] {
  return ["aux", "bbl", "bcf", "blg", "idx", "ilg", "ind", "lof", "lot", "out", "run.xml", "toc"].map((ext) =>
    path.join(outputDir, `${base}.${ext}`)
  );
}

function normalizeBibFiles(value: unknown): string[] {
  if (Array.isArray(value)) return value.filter((item): item is string => typeof item === "string");
  return typeof value === "string" ? [value] : [];
}

function biblatexStyle(csl: string): string {
  const normalized = csl.toLowerCase();
  if (normalized.includes("ieee")) return "ieee";
  if (normalized.includes("chicago")) return "authoryear";
  if (normalized.includes("vancouver")) return "numeric";
  return "apa";
}

function resolveSourceRelativePath(rawPath: string, document: DocumentNode, ctx: LatexContext): string {
  if (/^https?:\/\//.test(rawPath) || path.isAbsolute(rawPath)) return rawPath;
  const sourceFile = document.sourceFiles[0];
  if (!sourceFile) return rawPath;
  const absolute = path.resolve(path.dirname(sourceFile), rawPath);
  return path.relative(ctx.options.outputDir, absolute).replace(/\\/g, "/");
}

function resolveNodeRelativePath(rawPath: string, node: { position?: { file?: string } }, ctx: LatexContext): string {
  if (/^https?:\/\//.test(rawPath) || path.isAbsolute(rawPath)) return rawPath;
  if (!node.position?.file) return rawPath;
  const absolute = path.resolve(path.dirname(node.position.file), rawPath);
  return path.relative(ctx.options.outputDir, absolute).replace(/\\/g, "/");
}
